import Head from "next/head";

export default function Home() {
	console.log("I am home page");
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h2>Hello World</h2>
			</main>
		</>
	);
}
